### ISSUE TITLE
Please include a license

### ISSUE THREAD

**Issue by ajaysuwalka** [nextbigsoundinc/cypress-scenario-builder#1]
I want to use the code pattern that you have applied but I am frightened to do that as you don't have a license added to your repository which restricts me to do that. Can you please allow everyone to use the code structure as they want It would be so kind of you. 

thanks for making it open source

**Comment by mpetrovich** [comment]
Done: https://github.com/mpetrovich/gherkin-scenario-builder/blob/master/LICENSE
